# echo '{"auths":{"docker.pkg.github.com":{"auth":"<AUTH>"}}}' | kubectl create secret generic dockerconfigjson-github-com --type=kubernetes.io/dockerconfigjson --from-file=.dockerconfigjson=/dev/stdin
# auth
apiVersion: v1
kind: ConfigMap
metadata:
  name: ttestmap
  namespace: default
data:
  envtest: "ENV another test"
